name: combine_categorical_runs-env
dependencies:
  - boost
  - zlib
  - bzip2
  - git
# required for commitizen
  - nodejs
  - pre-commit
  - cppcheck
  - sarcasm::clang-format


  - automake
  - autoconf
  - make>=4.2
  - mpfr
